### ISSUE TITLE
inconsistency in Investment|Energy Supply|Liquids

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamInterfaces#15]
Dear colleagues,
a user noticed an inconsistency in NGFS results:
![image](https://user-images.githubusercontent.com/90761609/196376084-540dd971-b4c1-4bba-897e-764152dfeb48.png)

The corresponding mapping chain is ([NAVIGATE](https://github.com/pik-piam/piamInterfaces/blob/517de3882c7755f8e1d3891277b80a9f121dbc6c/inst/templates/mapping_template_NAVIGATE.csv#L1447-L1448) / [AR6](https://github.com/pik-piam/piamInterfaces/blob/517de3882c7755f8e1d3891277b80a9f121dbc6c/inst/templates/mapping_template_AR6.csv#L1466-L1467) / [remind2](https://github.com/pik-piam/remind2/blob/62fdc91be2fa10340e5a99ad988955a9ddf65cd0/R/reportEnergyInvestment.R#L156-L159)):
```
remindmodel    -> remind2 reporting                         -> NAVIGATE / AR6
peoil          -> Energy Investments|Liquids|Oil Ref        -> Investment|Energy Supply|Liquids|Oil
petyf          -> Energy Investments|Liquids|Fossil         -> Investment|Energy Supply|Liquids|Coal and Gas
pecoal + pegas -> Energy Investments|Liquids|Fossil|w/o oil -> not mapped
```
Maybe better to map `w/o oil` to `Coal and Gas`?

**Comment by Renato-Rodrigues** [comment]
This seams odd in the reporting code:
I am not familiar with the reportCosts code, but it seams quite odd for me in the reporting code the use of `petyf` for non-oil fossil, as far as I know `petyf=pefos=coal+gas+oil` (https://github.com/pik-piam/remind2/blob/62fdc91be2fa10340e5a99ad988955a9ddf65cd0/R/reportCosts.R#L562:L564) and the use of only coal in fossil investments instead of `coal+gas+oil` (https://github.com/pik-piam/remind2/blob/62fdc91be2fa10340e5a99ad988955a9ddf65cd0/R/reportCosts.R#L566:L568)

**Comment by christophbertram** [comment]
Yes, Oli, please correct the mapping in NAVTIGATE and AR6 as you suggest.
And on Renato's comment: I think you are right: These two lines most be swapped...

**Comment by orichters** [comment]
fixed in mapping and remind2 (Thanks, @Renato-Rodrigues, for spotting this)
