### ISSUE TITLE
Find solution for dropping aggregated regions in generateIIASASubmission

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamInterfaces#262]
Using REMIND EU21, EUR and NEU have to be dropped from the data to avoid that IIASA database does double-counting. For ECEMF, Renato also drops `World` before submission.

Oliver is reluctant to adding a general rule to `generateIIASASubmission` because it is used by multiple models and projects, but we should at least warn the user about such things.

The problem is that in a mif file, you cannot identify anymore which the aggregate regions are (apart from World, maybe).

As a current workaround, such a function can be used:
```
mifs %>%
  generateIIASASubmission(mapping = "ECEMF", model = "REMIND 3.2", outputDirectory = NULL) %>%
  dplyr::filter(! .data$region %in% c("World","EUR","NEU")) %>%
  quitte::write.IAMCxlsx("output/submission.xlsx")
```

**Comment by orichters** [comment]
The only solution I see is to add some sort of
```
if ("ECEMF" %in% mapping) mifdata <- filter(mifdata, ! .data$region %in% c("World","EUR","NEU"))
```
into `generateIIASASubmission()`. @Renato-Rodrigues: what do you think?

**Comment by Renato-Rodrigues** [comment]
This is not ECEMF specific. 
The drop should be done for any EU21 results reporting, as long as there was no change in the single file REMIND registration that I made to the iiasa database that works for both H21, EU21, and any future regional disaggregation.

**Comment by orichters** [comment]
- It would be great if you could add your registration files here: https://github.com/pik-piam/piamInterfaces/tree/master/inst/registration.
- Given "any future regional disaggregation": How would you identify the regions to be dropped based on the content of a mif file?
- How can we identify whether "World" should be dropped? By the way: what about the "EU27" region?
- For EU21, maybe just use:
```
EU21_regi <- c("CAZ", "CHA", "EUR", "IND", "JPN", "LAM", "MEA", "NEU", "OAS", "REF", "SSA", "USA", "DEU", "ECE", "ECS", "ENC", "ESC", "ESW", "EWN", "FRA", "UKI", "NEN", "NES", "EU27", "World")
if (setequal(EU21_regi, levels(mifdata$region))) mifdata <- filter(mifdata, ! .data$region %in% c("World","EUR","NEU"))
```
This would make sure we certainly don't interfere with any MAgPIE submission or so.

**Comment by Renato-Rodrigues** [comment]
> * It would be great if you could add your registration files here: https://github.com/pik-piam/piamInterfaces/tree/master/inst/registration.

I don't know what these registration files you are mentioned are for. I mentioned the REMIND registration at the iiasa official github: 
`https://github.com/IAMconsortium/common-definitions/blob/main/mappings/REMIND_3.1.yml`

**Comment by Renato-Rodrigues** [comment]
For now I would define the drop condition, and an accompanying warning, if the mif file contains one of the regions that is exclusive to REMIND-21.
I would not add any project specific condition.

**Comment by Renato-Rodrigues** [comment]
The World region drop is case dependable.
If you do any results post-processing, or if for example your project demands considering national bunker emissions or LULUCF alternative accountings, automatic REMIND aggregations would not necessarily match the results that you want to upload, and you would be better relying in iiasa automatic database calculations instead.

**Comment by orichters** [comment]
> > * It would be great if you could add your registration files here: https://github.com/pik-piam/piamInterfaces/tree/master/inst/registration.
> 
> I don't know what these registration files you are mentioned are for. I mentioned the REMIND registration at the iiasa official github: `https://github.com/IAMconsortium/common-definitions/blob/main/mappings/REMIND_3.1.yml`

Jakob asked in the REMIND channel in April where to find such a file, and nobody knew (or read the post), so I was asked by Lavinia to put these files there. The ELEVATE file is probably very similar to yours.

**Comment by Renato-Rodrigues** [comment]
The last time I spoke with iiasa about model registrations, they were gradually moving to have this handled centralized in the common-definitions repository instead of using a per project one.

So, I would remove those files from the piamInterfaces library, in order to avoid unnecessary duplicates and/or the creating of incompatible versions, and rely in the iiasa main repository created exactly for this reason to have these files.

I would only add to the piamInterfaces library either (a) the information with the path of the iiasa common-definitions repository in the documentation, or (2) a function to automatically download this file from the official repository directly.

For any new official REMIND release, I would directly do a pull request to the iiasa common-definitions with any necessary adaptations needed in the REMIND model registration file.
@LaviniaBaumstark any thoughts about this?

> Jakob asked in the REMIND channel in April where to find such a file, and nobody knew (or read the post), so I was asked by Lavinia to put these files there. The ELEVATE file is probably very similar to yours.

I remember reading Jakob message, but as far as I remember he was asking specifically for the 3.3. registration file, which I didn't have done at the time, so I did not replied to that at the time.
